

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;                                                      ;;;;
    ;;;;                    GSDO/AIA                          ;;;;
    ;;;;                                                      ;;;;
    ;;;;       Main code for automated eruption detection     ;;;;
    ;;;;       on SDO/AIA 171/304 A images.                   ;;;;
    ;;;;                                                      ;;;;
    ;;;;       D.Gronkiewicz 2015-2016                        ;;;;
    ;;;;       Master Thesis                                  ;;;;
    ;;;;                                                      ;;;;
    ;;;;                                                      ;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;



    ; IMPORTANT
    ; Do not edit this file to avoid GIT conflicts!
    ; Make a copy called "gsdo_start.pro" and put your settings there.


    start_time  = '29-apr-2012 14:30'
    end_time    = '29-apr-2012 18:30'

    interval    = (60*3)*60l
    wave        = 171

    ; clean fits folder after a successful epoch?
    clean_fits_folder = 1

    ; maximum number of retries for a failed job
    max_job_retries = 3
    
    ; time to cool down after an error
    cooldown_period_sec = 60 

    marg = 1

    error_handling = 1

    set_plot,'Z'

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    gsdo_log, 'STARTING ===== ' + anytim(start_time,/yoh,/trunc) + ' - ' + anytim(end_time,/yoh,/trunc)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    sl = path_sep()

    ; directory where fits files are stored
    fits_dir = getenv('GSDO_DATA') + sl + "fits"
    sav_dir = getenv('GSDO_DATA') + sl + 'sav'

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


    t0 = anytim(start_time)

    anchfn = sav_dir + sl + 'anchor.sav'
    if (FILE_SEARCH(anchfn))[0] ne '' then begin
        restore, filename = anchfn
        t = anytim(time_finished)
        if (t gt anytim(start_time)) and (t lt anytim(end_time)) then begin
            gsdo_log, 'Restoring saved point ' + anytim(t,/yoh,/trunc)
            t0 = t
        endif
    endif

    t1 = t0 + interval
    fails = 0


    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


    while t1 le anytim(end_time) do begin

        if error_handling then begin
            catch, err
            if err ne 0 then begin
                fails = fails + 1
                print,'  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR !!!!!!!!'
                print, !ERROR_STATE.MSG
                print, !ERROR_STATE.sys_msg
                gsdo_log, 'Severe error on interval: ' + anytim(t0,/yoh,/trunc) + ' - ' + anytim(t1,/yoh,/trunc)
                if fails ge max_job_retries then begin
                    gsdo_log, "Retry number exceeded, skipping..."
                    t0 = t1 & t1 = t0 + interval
                    fails = 0
                endif else begin
                    gsdo_log, "Cooling down..."
                    wait, cooldown_period_sec
                    gsdo_log, "Retrying the job..."
                endelse
                catch,/cancel
                continue
            endif
        endif

        pushd, fits_dir
        print, 'Downloading data...'

        gsdo_synop_get, anytim(t0 - marg*2*60. - 1), anytim(t1 + marg*2*60. + 1), filter = wave, /verb
        popd

        fn = FILE_SEARCH(fits_dir + path_sep() + '*.fits', /FOLD_CASE)

        if fn[0] eq '' then begin
            message, 'error: no files'
        endif

        eruptions = gsdo_process(fn,                    $
                prob_threshold = 0.35,                  $
                blur_image = 2.8,                       $
                blur_apriori = 7.0,                     $
                transform_param = 8.0,                  $
                area_threshold = 600,                   $
                map_max_tiles = 14,                     $
                n_points_min = 10,			            $
                erupt_movement_threshold = 25,          $
                erupt_intensity_threshold = 30,         $
                prob_space_blur = [3., 2.],             $
                n_found = n_found,                      $
                w_param = 8)

        gsdo_log, 'FINISHED ('+anytim(t0,/yoh,/trunc) + ' - ' + anytim(t1,/yoh,/trunc)+')'
        gsdo_log, '     found eruptions ' + string(n_found)

        time_finished = t1
        save, filename = anchfn, time_finished

        t0 = t1 & t1 = t0 + interval
        fails = 0

        if clean_fits_folder ne 0 then begin
            ; clean up

            fn0 = FILE_SEARCH(fits_dir + path_sep() + '*.fits', /FOLD_CASE)

            if fn0[0] ne '' then begin
                file_delete, fn0, /allow_nonexistent
            endif

        endif

    endwhile

   gsdo_log, ' === JOB ENDED ==='

end
