

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;                                                      ;;;;
    ;;;;                    GSDO/AIA                          ;;;;
    ;;;;                                                      ;;;;
    ;;;;       Main code for automated eruption detection     ;;;;
    ;;;;       on SDO/AIA 171/304 A images.                   ;;;;
    ;;;;                                                      ;;;;
    ;;;;       D.Gronkiewicz 2015-2026                        ;;;;
    ;;;;       Master Thesis                                  ;;;;
    ;;;;                                                      ;;;;
    ;;;;                                                      ;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;



    ; IMPORTANT
    ; Do not edit this file!
    ; Make a copy called "gsdo_start.pro" and put your settings there.
    ;
    ;   cp gsdo_start.default.pro gsdo_start.pro


    start_time  = '23-apr-2024 01:30'
    end_time    = '23-apr-2024 07:30'

    ; processing interval length in seconds (default: 3h)
    interval    = (60*3)*60l

    ; AIA wavelength
    wave        = 171

    ; clean fits folder after a successful epoch?
    ; set to 0 if you plan to rerun on the same period
    clean_fits_folder = 1

    ; if set to 0, the program will crash if the failure occurs.
    ; turn on for normal operation, turn off for debugging
    error_handling = 1
    
    ; maximum number of retries for a failed job
    max_job_retries = 2
    
    ; time to cool down after an error. useful if issues
    ; are related mostly to networking
    cooldown_period_sec = 120 

    ; algorithm settings

    prob_threshold = 0.35            ; threshold for determining the eruption contours
    blur_image = 2.8                 ; blur image by this kernel before processing
    blur_apriori = 7.0               ; blur probability map by this kernel before extraction
    transform_param = 8.0            ; filter depentent noise suppression parameter (8.0 for AIA 171)
    area_threshold = 600             ; reject candidates below this are
    map_max_tiles = 14               ; divide image into this many tiles when computing variability
    n_points_min = 10                ; reject candidates which span less than this number of frames
    erupt_movement_threshold = 25    ; reject candidates which centroid moved less than this
    erupt_intensity_threshold = 30   ; reject candidates with intensity less than this
    prob_space_blur = [3., 2.]       ; blur intensity X variability space with this kernel
    w_param = 8.                     ; how much variability (ratio to intensity) 
                                     ; contributes to finding quiet frames 
    reject_head_tail = 1             ; how many frames to add before and after each 
                                     ; processing interval (minimum: 1)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    gsdo_log, 'STARTING ===== ' + anytim(start_time,/yoh,/trunc) + ' - ' + anytim(end_time,/yoh,/trunc)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    sl = path_sep()

    ; directory where fits files are stored
    fits_dir = getenv('GSDO_DATA') + sl + "fits"
    sav_dir = getenv('GSDO_DATA') + sl + 'sav'

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


    t0 = anytim(start_time)

    anchfn = sav_dir + sl + 'anchor.sav'
    if (FILE_SEARCH(anchfn))[0] ne '' then begin
        restore, filename = anchfn
        t = anytim(time_finished)
        if (t gt anytim(start_time)) and (t lt anytim(end_time)) then begin
            gsdo_log, 'Restoring saved point ' + anytim(t,/yoh,/trunc)
            t0 = t
        endif
    endif

    t1 = t0 + interval
    fails = 0

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    while t1 le anytim(end_time) do begin

        if error_handling then begin
            catch, err
            if err ne 0 then begin
                fails = fails + 1
                print,'  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR !!!!!!!!'
                print, !ERROR_STATE.MSG
                print, !ERROR_STATE.sys_msg
                gsdo_log, 'Severe error on interval: ' + anytim(t0,/yoh,/trunc) + ' - ' + anytim(t1,/yoh,/trunc)
                if fails ge max_job_retries then begin
                    gsdo_log, "Retry number exceeded, skipping..."
                    t0 = t1 & t1 = t0 + interval
                    fails = 0
                endif else begin
                    gsdo_log, "Cooling down..."
                    wait, cooldown_period_sec
                    gsdo_log, "Retrying the job..."
                endelse
                catch,/cancel
                continue
            endif
        endif

        pushd, fits_dir
        print, 'Downloading data...'
        local_names = [""]
        gsdo_synop_get, anytim(t0 - reject_head_tail*120. - 1), $
            anytim(t1 + reject_head_tail*120. + 1), filter = wave, local_names=local_names, /verb
        popd

        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        ;;;;;;;;;;;;;;;;        MORE SETTINGS BELOW    ;;;;;;;;;;;;;;;;;;;;;;;;
        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        eruptions = gsdo_process(fits_dir + sl + local_names,  $
                prob_threshold = prob_threshold, $
                blur_image = blur_image, $
                blur_apriori = blur_apriori, $
                transform_param = transform_param, $
                area_threshold = area_threshold, $
                map_max_tiles = map_max_tiles, $
                n_points_min = n_points_min, $
                erupt_movement_threshold = erupt_movement_threshold, $
                erupt_intensity_threshold = erupt_intensity_threshold, $
                prob_space_blur = prob_space_blur ,              $
                n_found = n_found,                      $
                reject_head_tail = reject_head_tail,     $
                w_param = w_param)

        gsdo_log, 'FINISHED ('+anytim(t0,/yoh,/trunc) + ' - ' + anytim(t1,/yoh,/trunc)+')'
        gsdo_log, '     found eruptions ' + string(n_found)

        time_finished = t1
        save, filename = anchfn, time_finished

        t0 = t1 & t1 = t0 + interval
        fails = 0

        if clean_fits_folder ne 0 then begin
            file_delete, fits_dir + sl + local_names, /allow_nonexistent
        endif

    endwhile

   gsdo_log, ' === JOB ENDED ==='

end
